# Generated by Django 5.1.5 on 2025-01-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_training', '0002_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='in_scope',
            field=models.BooleanField(default=False, help_text='If the division is target for the training program, check this field.'),
            preserve_default=False,
        ),
    ]
