# Generated by Django 5.1.5 on 2025-01-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_training', '0009_learningcourse_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcourse',
            name='extra',
        ),
    ]
